# Generated by Django 4.2 on 2023-04-25 09:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20)),
                ('guesses', models.CharField(default='', max_length=100)),
                ('max_guesses', models.PositiveIntegerField(default=5)),
                ('remaining_guesses', models.PositiveIntegerField(default=5)),
                ('is_over', models.BooleanField(default=False)),
                ('is_winner', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hangman.player')),
            ],
        ),
    ]
