# Generated by Django 4.2 on 2023-04-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_authenticated',
            field=models.BooleanField(default=True),
        ),
    ]
