# Generated by Django 4.2 on 2023-04-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0003_remove_game_player_game_user_delete_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
