# Generated by Django 4.2 on 2023-04-25 19:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0004_game_is_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
